//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSTournamentsBot.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class S {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal S() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSTournamentsBot.Api.Resources.S", typeof(S).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Следующее событие &apos;**{0}**&apos; отложено на **{1}**.
        /// </summary>
        public static string AddTime_NextEventDelayed {
            get {
                return ResourceManager.GetString("AddTime_NextEventDelayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Следующее событие &apos;**{0}**&apos; ускорено на -**{1}**.
        /// </summary>
        public static string AddTime_NextEventSpeedUp {
            get {
                return ResourceManager.GetString("AddTime_NextEventSpeedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Сейчас нет запланированных событий..
        /// </summary>
        public static string AddTime_NoEvents {
            get {
                return ResourceManager.GetString("AddTime_NoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Нет изменений во времени следующего события, так как указано 0 минут..
        /// </summary>
        public static string AddTime_NoMinutes {
            get {
                return ResourceManager.GetString("AddTime_NoMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Ваш список банов успешно обновлен, но изменения будут учтены только на следующих турнирах..
        /// </summary>
        public static string BanMaps_MapsUpdatedButForNextTournaments {
            get {
                return ResourceManager.GetString("BanMaps_MapsUpdatedButForNextTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Ваш список банов успешно обновлен..
        /// </summary>
        public static string BanMaps_UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("BanMaps_UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} исключен из активности..
        /// </summary>
        public static string BanPlayer_Kicked {
            get {
                return ResourceManager.GetString("BanPlayer_Kicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка аккаунта завершена успешно. Добро пожаловать на участие в соревновательных активностях бота. Выполните команду __**/play повторно**__ на канале проведения интересующего события, чтобы зарегистрироваться..
        /// </summary>
        public static string Bot_AccountRegisteredSuccessfully {
            get {
                return ResourceManager.GetString("Bot_AccountRegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;h1&gt;SS Tournaments Bot by elamaunt&lt;/h1&gt;&lt;br/&gt;&lt;p&gt;Привязка аккаунта завершена успешно. Добро пожаловать на участие в турнирах! Выполните команду play повторно на турнирном канале в Discord, чтобы зарегистрироваться.&lt;/p&gt;.
        /// </summary>
        public static string Bot_AccountRegisteredSuccessfullyHtml {
            get {
                return ResourceManager.GetString("Bot_AccountRegisteredSuccessfullyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Вы уже покинули данную активность..
        /// </summary>
        public static string Bot_AreAlreadyLeftTheEvent {
            get {
                return ResourceManager.GetString("Bot_AreAlreadyLeftTheEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Вы не были зарегистрированы..
        /// </summary>
        public static string Bot_AreNotregisteredInEvent {
            get {
                return ResourceManager.GetString("Bot_AreNotregisteredInEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данная команда еще не реализована..
        /// </summary>
        public static string Bot_CommandNotImplemented {
            get {
                return ResourceManager.GetString("Bot_CommandNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Не удалось обновить данные в базе..
        /// </summary>
        public static string Bot_DataBaseUpdateError {
            get {
                return ResourceManager.GetString("Bot_DataBaseUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привет, друзья! 
        ///**SS Tournaments Bot** к вашим услугам и готов устраивать для Вас ивенты.
        ///Для регистрации на них используйте **/slash** команды.
        ///Удачной игры!**.
        /// </summary>
        public static string Bot_Greetings {
            get {
                return ResourceManager.GetString("Bot_Greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Не удалось обновить данные в базе..
        /// </summary>
        public static string Bot_ImposibleToUpdateDataBase {
            get {
                return ResourceManager.GetString("Bot_ImposibleToUpdateDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Нет активности..
        /// </summary>
        public static string Bot_NoActiveTournament {
            get {
                return ResourceManager.GetString("Bot_NoActiveTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сейчас нет запланированных событий..
        /// </summary>
        public static string Bot_NoEvents {
            get {
                return ResourceManager.GetString("Bot_NoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Такого пользователя не существует..
        /// </summary>
        public static string Bot_NoUserInDataBase {
            get {
                return ResourceManager.GetString("Bot_NoUserInDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такой SteamId уже зарегистрирован на другого пользователя..
        /// </summary>
        public static string Bot_SteamIdAlreadyUsedHtml {
            get {
                return ResourceManager.GetString("Bot_SteamIdAlreadyUsedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;p&gt;Не удалось загрузить информацию о вашем пользователе, либо SteamId не был обнаружен.&lt;/p&gt;.
        /// </summary>
        public static string Bot_SteamIdNotFoundHtml {
            get {
                return ResourceManager.GetString("Bot_SteamIdNotFoundHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;&gt;&gt; В данный момент активность уже идет..
        /// </summary>
        public static string Bot_TournamentInProgress {
            get {
                return ResourceManager.GetString("Bot_TournamentInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;&gt;&gt; Активность еще не началась.
        /// </summary>
        public static string Bot_TournamentNotStartedYet {
            get {
                return ResourceManager.GetString("Bot_TournamentNotStartedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестная команда &apos;{0}&apos;..
        /// </summary>
        public static string Bot_UnknownCommand {
            get {
                return ResourceManager.GetString("Bot_UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Вы не зарегистрированы в системе..
        /// </summary>
        public static string Bot_YouAreNotRegistered {
            get {
                return ResourceManager.GetString("Bot_YouAreNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Твой оппонент под ником **{opponent.Name}** вызван через личные сообщения..
        /// </summary>
        public static string Call_CalledSuccessfully {
            get {
                return ResourceManager.GetString("Call_CalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Игрок под ником {0} призывает тебя начать матч. Пожалуйста, свяжись с ним в чат канале активности..
        /// </summary>
        public static string Call_DirectMessageText {
            get {
                return ResourceManager.GetString("Call_DirectMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Возникла ошибка при вызове игрока.
        /// </summary>
        public static string Call_Error {
            get {
                return ResourceManager.GetString("Call_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;&gt;&gt; Твой оппонент под ником **{0}** не может быть вызван. Возможно, он покинул сервер.\nЕму будет присуждено техническое поражение..
        /// </summary>
        public static string Call_ImposibleToComply {
            get {
                return ResourceManager.GetString("Call_ImposibleToComply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; В данный момент ваш оппонент еще не определен..
        /// </summary>
        public static string Call_NoOpponent {
            get {
                return ResourceManager.GetString("Call_NoOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; {0} исключен из турнира, так как недоступен..
        /// </summary>
        public static string Call_UserKickedFromTournament {
            get {
                return ResourceManager.GetString("Call_UserKickedFromTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; У вас нет активных матчей в данный момент..
        /// </summary>
        public static string Call_YouHaveNotActiveMatches {
            get {
                return ResourceManager.GetString("Call_YouHaveNotActiveMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Вы успешно подтведили свое участие!.
        /// </summary>
        public static string CheckIn_CheckInedSuccessfully {
            get {
                return ResourceManager.GetString("CheckIn_CheckInedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Произошла ошибка.
        /// </summary>
        public static string CheckIn_Error {
            get {
                return ResourceManager.GetString("CheckIn_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; В данный момент чекин не проводится..
        /// </summary>
        public static string CheckIn_NotActiveNow {
            get {
                return ResourceManager.GetString("CheckIn_NotActiveNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Вы уже подтведили свое участие..
        /// </summary>
        public static string CheckIn_YouAreAlreadyCheckined {
            get {
                return ResourceManager.GetString("CheckIn_YouAreAlreadyCheckined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Вы не зарегистрированы в системе. Используйте команду */play*..
        /// </summary>
        public static string CheckIn_YouAreNotRegisteredInTheSystem {
            get {
                return ResourceManager.GetString("CheckIn_YouAreNotRegisteredInTheSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Вы не регистрировались на текущую активность..
        /// </summary>
        public static string CheckIn_YouAreNotRegisteredInTournament {
            get {
                return ResourceManager.GetString("CheckIn_YouAreNotRegisteredInTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;&gt;&gt; Начинается следующая стадия! Генерация сетки...
        /// </summary>
        public static string Event_NextStageStarted {
            get {
                return ResourceManager.GetString("Event_NextStageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание! Началась стадия чекина *{0} AutoCup {1}*.\nВсем участникам нужно выполнить команду __**/checkin**__ на канале активности для подтверждения своего участия.\nДлительность чек-ина {2} минут.\nРегистрация открыта до окончания чекина, при этом новым участникам вызов команды */checkin* не требуется, достаточно команды */play*.
        /// </summary>
        public static string Events_ActivityCheckinStarted {
            get {
                return ResourceManager.GetString("Events_ActivityCheckinStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на __**{0} успешно завершен**__\n==================================================================================================\n.
        /// </summary>
        public static string Events_ActivityCompleted {
            get {
                return ResourceManager.GetString("Events_ActivityCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Определился победитель, но турнир не будет засчитан, так как он полностью состоит из технических поражений. Должна быть сыграна хотя бы одна игра..
        /// </summary>
        public static string Events_ActivityNotCounted {
            get {
                return ResourceManager.GetString("Events_ActivityNotCounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начинается активность *{0} AutoCup {1}*!.
        /// </summary>
        public static string Events_ActivityStarted {
            get {
                return ResourceManager.GetString("Events_ActivityStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на __**{0}**__ благополучно завершен!\nПоздравляем с победой игрока под ником __**{1}**__. Всем остальным желаем удачи на следующих турнирах!.
        /// </summary>
        public static string Events_ArchiveHeader {
            get {
                return ResourceManager.GetString("Events_ArchiveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сетка:.
        /// </summary>
        public static string Events_Bracket {
            get {
                return ResourceManager.GetString("Events_Bracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;&gt;&gt; **Матчи, которые должны быть сыграны в текущей стадии турнира:**.
        /// </summary>
        public static string Events_CurrentStageMatches {
            get {
                return ResourceManager.GetString("Events_CurrentStageMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;&gt;&gt; Быстрое голосование по незавершенному матчу. Кому присудить техническое поражение?.
        /// </summary>
        public static string Events_FastVotingForUncompletedMatch {
            get {
                return ResourceManager.GetString("Events_FastVotingForUncompletedMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на __**{0} завершен без учета результатов**__\n==================================================================================================\n.
        /// </summary>
        public static string Events_FinishedWithNoResults {
            get {
                return ResourceManager.GetString("Events_FinishedWithNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Первая стадия турнира началась. Пошел отсчет времени __**{TimeSpan.FromMinutes(_options.StageTimeoutMinutes).PrettyPrint()}**__ до конца стадии..
        /// </summary>
        public static string Events_FirstStageStarted {
            get {
                return ResourceManager.GetString("Events_FirstStageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полная сетка:.
        /// </summary>
        public static string Events_FullBracket {
            get {
                return ResourceManager.GetString("Events_FullBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---\nИгру хостят вот эти ребята:.
        /// </summary>
        public static string Events_Hosts {
            get {
                return ResourceManager.GetString("Events_Hosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблица лидеров была обновлена..
        /// </summary>
        public static string Events_LeaderboardHasBeenUpdated {
            get {
                return ResourceManager.GetString("Events_LeaderboardHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --- __**Таблица лидеров**__ ---.
        /// </summary>
        public static string Events_LeaderBoardHeader {
            get {
                return ResourceManager.GetString("Events_LeaderBoardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Московское время {0}\nСледующее событие &apos;**{1}**&apos; наступит через **{2}**..
        /// </summary>
        public static string Events_NextEvent {
            get {
                return ResourceManager.GetString("Events_NextEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Без турниров сегодня :).
        /// </summary>
        public static string Events_NoTournamentsToday {
            get {
                return ResourceManager.GetString("Events_NoTournamentsToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;&gt;&gt; Сыгранные матчи:.
        /// </summary>
        public static string Events_PlayedMatches {
            get {
                return ResourceManager.GetString("Events_PlayedMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---\nНа скамейке отдыхающих на этот раз:.
        /// </summary>
        public static string Events_Relaxing {
            get {
                return ResourceManager.GetString("Events_Relaxing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на **Не забывайте использовать DowStats и прикрепленный Steam аккаунт, иначе матч не будет засчитан!**.
        /// </summary>
        public static string Events_RulesRemind {
            get {
                return ResourceManager.GetString("Events_RulesRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Единственный матч в этой стадии еще не доигран. Завершение стадии отложено на __**5 минут.**__.
        /// </summary>
        public static string Events_SingleMatchNotFinished {
            get {
                return ResourceManager.GetString("Events_SingleMatchNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стадия была успешно завершена! Следующая стадия начнется после {0}-минутного перерыва..
        /// </summary>
        public static string Events_StageCompleted {
            get {
                return ResourceManager.GetString("Events_StageCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Половина или более матчей еще не доиграны. Завершение стадии отложено на __**5 минут**__..
        /// </summary>
        public static string Events_StageCompletionDelayed {
            get {
                return ResourceManager.GetString("Events_StageCompletionDelayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая стадия началась. Пошел отсчет времени __**{0}**__ до конца стадии..
        /// </summary>
        public static string Events_StageTimeInfo {
            get {
                return ResourceManager.GetString("Events_StageTimeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Присуждено техническое поражение игроку под ником **{0}**..
        /// </summary>
        public static string Events_TechLoseToPlayer {
            get {
                return ResourceManager.GetString("Events_TechLoseToPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Турнир отменен, так как участников недостаточно. Список зарегистрированных был обнулен.\nСледующий турнир начнется, когда снова зарегистрируются {0} участника..
        /// </summary>
        public static string Events_TournamentCancelledNoPlayers {
            get {
                return ResourceManager.GetString("Events_TournamentCancelledNoPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В данный момент активность невозможно начать, так как участников недостаточно.\nМинимальное количество участников 4.\nСписок зарегистрированных был обнулен..
        /// </summary>
        public static string Events_UnableToStartNoPlayers {
            get {
                return ResourceManager.GetString("Events_UnableToStartNoPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Результат голосования не принят, так как матч был завершен..
        /// </summary>
        public static string Events_VotingCancelledCauseMatchFinished {
            get {
                return ResourceManager.GetString("Events_VotingCancelledCauseMatchFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Голосование завершено..
        /// </summary>
        public static string Events_VotingHasBeenEnded {
            get {
                return ResourceManager.GetString("Events_VotingHasBeenEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;&gt;&gt; Результат голосования не принят, так как голоса разделились поровну, либо никто не проголосовал.\nНо решение все равно нужно принять, поэтому техническое поражение выдается игроку на усмотрение бота..
        /// </summary>
        public static string Events_VotingResultNotDefined {
            get {
                return ResourceManager.GetString("Events_VotingResultNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Определился победитель турнира!.
        /// </summary>
        public static string Events_WeGotWinner {
            get {
                return ResourceManager.GetString("Events_WeGotWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Следующее событие было форсировано..
        /// </summary>
        public static string ForceEvent_Done {
            get {
                return ResourceManager.GetString("ForceEvent_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Сейчас нет запланированных событий..
        /// </summary>
        public static string ForceEvent_NoEvents {
            get {
                return ResourceManager.GetString("ForceEvent_NoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пока никто не зарегистрировался, но, возможно, вы будете первым :).
        /// </summary>
        public static string Info_NobodyRegisteredMessage {
            get {
                return ResourceManager.GetString("Info_NobodyRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрировано участников: {0}.
        /// </summary>
        public static string Info_RegisteredPlayers {
            get {
                return ResourceManager.GetString("Info_RegisteredPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип турнира: {0}.
        /// </summary>
        public static string Info_TournamentType {
            get {
                return ResourceManager.GetString("Info_TournamentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Игрок уже был забанен..
        /// </summary>
        public static string KickPlayer_AlreadyBanned {
            get {
                return ResourceManager.GetString("KickPlayer_AlreadyBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Игрок уже был исключен из активности администрацией..
        /// </summary>
        public static string KickPlayer_AlreadyKickedByAdmin {
            get {
                return ResourceManager.GetString("KickPlayer_AlreadyKickedByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Игрок уже покинул эту активность..
        /// </summary>
        public static string KickPlayer_AlreadyLeftTheTournament {
            get {
                return ResourceManager.GetString("KickPlayer_AlreadyLeftTheTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Нельзя исключить игрока из активност, в которой он не зарегистрирован..
        /// </summary>
        public static string KickPlayer_ImposibleToKickNotRegisteredPlayer {
            get {
                return ResourceManager.GetString("KickPlayer_ImposibleToKickNotRegisteredPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Вы не можете покинуть активность, так как вы уже покинули ее путем голосования..
        /// </summary>
        public static string KickPlayer_ImposibleToLeaveWhenAlreadyLeftByVoting {
            get {
                return ResourceManager.GetString("KickPlayer_ImposibleToLeaveWhenAlreadyLeftByVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Не удалось исключить игрока из активности..
        /// </summary>
        public static string KickPlayer_NotSucceded {
            get {
                return ResourceManager.GetString("KickPlayer_NotSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Пользователь не зарегистрирован в системе..
        /// </summary>
        public static string KickPlayer_NoUser {
            get {
                return ResourceManager.GetString("KickPlayer_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Игрок **{0}** покинул активность..
        /// </summary>
        public static string KickPlayer_PlayerLeftTournament {
            get {
                return ResourceManager.GetString("KickPlayer_PlayerLeftTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Вы не можете покинуть активность, так как вы были забанены..
        /// </summary>
        public static string Leave_ImposibleToLeaveCauseBanned {
            get {
                return ResourceManager.GetString("Leave_ImposibleToLeaveCauseBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Вы не можете покинуть турнир, так как вы были исключены из него администрацией..
        /// </summary>
        public static string Leave_ImposibleToLeaveCauseKickedByAdmin {
            get {
                return ResourceManager.GetString("Leave_ImposibleToLeaveCauseKickedByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Вы покинули текущую активность..
        /// </summary>
        public static string Leave_Successfull {
            get {
                return ResourceManager.GetString("Leave_Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Вы не можете покинуть активность, так как вы уже покинули ее путем голосования..
        /// </summary>
        public static string Leave_YouAreAlreadyKickedByVoting {
            get {
                return ResourceManager.GetString("Leave_YouAreAlreadyKickedByVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Активность уже началась, изменения в данный момент невозможны..
        /// </summary>
        public static string Play_ActivityStarted {
            get {
                return ResourceManager.GetString("Play_ActivityStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;&gt;&gt; Вы уже зарегистрированы на активность.\nАккаунт на DowStats: {0} \nВыбранная раса: {1}.
        /// </summary>
        public static string Play_AlreadyRegistered {
            get {
                return ResourceManager.GetString("Play_AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;&gt;&gt; Вы уже зарегистрированы на активность, но смена расы на данный момент невозможна.\nАккаунт на DowStats: {0} \nВыбранная раса: {1}.
        /// </summary>
        public static string Play_AlreadyRegisteredButNoChanges {
            get {
                return ResourceManager.GetString("Play_AlreadyRegisteredButNoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Не удалось выполнить регистрацию..
        /// </summary>
        public static string Play_Imposible {
            get {
                return ResourceManager.GetString("Play_Imposible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для участия в активностях бота нужно подтвердить связь своей учетной записи со Steam. 
        ///Для этого нужно сперва добавить учетную запись стим в интеграции в настройках профиля вашего Discord аккаунта. 
        ///Сделать интеграцию видимой публично и затем перейти по ссылке ниже для подтверждения. Регистрироваться на активности могут только Steam аккаунты, имеющие не менее 300 сыгранных игр всего в сервисе DowStats..
        /// </summary>
        public static string Play_InstructionsMessage {
            get {
                return ResourceManager.GetString("Play_InstructionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;&gt;&gt;&gt; Недостаточно игр на аккаунте Steam.\nРегистрироваться на турнирах могут только Steam аккаунты, имеющие не менее **300 сыгранных игр** всего в сервисе DowStats.\nВозвращайтесь, когда наиграете больше игр :).
        /// </summary>
        public static string Play_NotEnoughGames {
            get {
                return ResourceManager.GetString("Play_NotEnoughGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;&gt;&gt; Для регистрации в системе необходимо присоединить Steam аккаунт к вашему профилю. Инструкция отправлена в личные сообщения..
        /// </summary>
        public static string Play_RegisterIntroMessage {
            get {
                return ResourceManager.GetString("Play_RegisterIntroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;&gt;&gt; Вы были успешно зарегистрированы на активность.\nАккаунт на DowStats: {0} \nВыбранная раса: {1}.
        /// </summary>
        public static string Play_Successfull {
            get {
                return ResourceManager.GetString("Play_Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;&gt;&gt; Вы были успешно зарегистрированы и зачекинены на активность.\nАккаунт на DowStats: {0} \nВыбранная раса: {1}.
        /// </summary>
        public static string Play_SuccessfullAndChekined {
            get {
                return ResourceManager.GetString("Play_SuccessfullAndChekined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В данный момент никто не зарегистрирован на активность..
        /// </summary>
        public static string Players_NobodyRegistered {
            get {
                return ResourceManager.GetString("Players_NobodyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Засчитана победа **{0}** в матче против **{1}**.\nСсылка на игру: {2}.
        /// </summary>
        public static string Scanner_MatchAccepted {
            get {
                return ResourceManager.GetString("Scanner_MatchAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Следующее событие &apos;**{0}**&apos; наступит через **{1}**..
        /// </summary>
        public static string Time_NextEvent {
            get {
                return ResourceManager.GetString("Time_NextEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt;&gt;&gt; Ваше время **&lt;t:{0}:t&gt;**\nМосковское время **{1}**.
        /// </summary>
        public static string Time_Time {
            get {
                return ResourceManager.GetString("Time_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Активности вас не побеспокоят.
        /// </summary>
        public static string Wait_Disabled {
            get {
                return ResourceManager.GetString("Wait_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; Вы будете получать уведомления о начинающихся активностях.
        /// </summary>
        public static string Wait_Enabled {
            get {
                return ResourceManager.GetString("Wait_Enabled", resourceCulture);
            }
        }
    }
}
